name: Run Code (No npm install)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run a sample script
        run: echo "Code checkout successful ✅"
